"""Provider-neutral infrastructure management protocol."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from mana_agent.server.models import (
    CreateServerRequest,
    ProviderServer,
    ProvisionedServer,
    Region,
    ServerImage,
    ServerSize,
)


@runtime_checkable
class ServerProvider(Protocol):
    name: str

    async def list_regions(self) -> list[Region]: ...
    async def list_sizes(self) -> list[ServerSize]: ...
    async def list_images(self) -> list[ServerImage]: ...
    async def create_server(self, request: CreateServerRequest) -> ProvisionedServer: ...
    async def inspect_server(self, server_id: str) -> ProviderServer: ...
    async def start_server(self, server_id: str) -> None: ...
    async def stop_server(self, server_id: str) -> None: ...
    async def reboot_server(self, server_id: str) -> None: ...
    async def resize_server(self, server_id: str, size: str) -> None: ...
    async def delete_server(self, server_id: str) -> None: ...
    async def create_snapshot(self, server_id: str, name: str) -> str: ...
