"""Common worker installer protocol."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol


class WorkerInstaller(Protocol):
    def install(self, *, executable: str | None = None) -> Path: ...
    def uninstall(self) -> None: ...
    def status(self) -> bool: ...
    def logs(self) -> str: ...
    def reconnect(self) -> None: ...
