from __future__ import annotations
from abc import ABC, abstractmethod
from mana_agent.connectors.email.models import *

class EmailProvider(ABC):
    @abstractmethod
    async def connect(self) -> EmailAccount: ...
    @abstractmethod
    async def disconnect(self) -> None: ...
    @abstractmethod
    async def health_check(self) -> ProviderHealth: ...
    @abstractmethod
    async def get_account(self) -> EmailAccount: ...
    @abstractmethod
    async def get_capabilities(self) -> EmailProviderCapabilities: ...
    @abstractmethod
    async def list_folders(self) -> list[EmailFolder]: ...
    @abstractmethod
    async def search_messages(self, query: EmailQuery, cursor: str | None = None) -> EmailSearchResult: ...
    @abstractmethod
    async def get_message(self, message_id: str) -> EmailMessage: ...
    @abstractmethod
    async def get_thread(self, thread_id: str) -> EmailThread: ...
    @abstractmethod
    async def get_attachment(self, message_id: str, attachment_id: str) -> EmailAttachment: ...
    @abstractmethod
    async def create_draft(self, draft: DraftInput) -> EmailDraft: ...
    @abstractmethod
    async def update_draft(self, draft_id: str, draft: DraftInput) -> EmailDraft: ...
    @abstractmethod
    async def delete_draft(self, draft_id: str) -> None: ...
    @abstractmethod
    async def send_draft(self, draft_id: str) -> SendResult: ...
    @abstractmethod
    async def send_message(self, message: SendInput) -> SendResult: ...
    @abstractmethod
    async def reply(self, message_id: str, reply: ReplyInput) -> SendResult: ...
    @abstractmethod
    async def reply_all(self, message_id: str, reply: ReplyInput) -> SendResult: ...
    @abstractmethod
    async def forward(self, message_id: str, forward: ForwardInput) -> SendResult: ...
    @abstractmethod
    async def modify_message(self, message_id: str, changes: MessageChanges) -> EmailMessage: ...
