"""Public provider-neutral memory API."""

from mana_agent.memory.config import CapsuleConfig, CapsuleRetentionConfig, MemoryConfig, MemorySecretStore
from mana_agent.memory.contracts import CapsuleBackend, MemoryBackend
from mana_agent.memory.capsules.models import (
    AuthorizationDecision,
    CapsuleLineage,
    CapsuleMergeRecord,
    CapsuleProjection,
    CapsuleReadRequest,
    CapsuleScope,
    CapsuleTaskContext,
    DeleteMode,
    MemoryCapsule,
    MemoryPrincipal,
    MergeState,
    MergeStrategy,
    ReviewState,
    TrustState,
)
from mana_agent.memory.capsules.service import (
    CapsuleAuthorizationError,
    CapsuleMergeConflict,
    CapsuleService,
)
from mana_agent.memory.errors import (
    MemoryAuthenticationError,
    MemoryConfigurationError,
    MemoryDependencyError,
    MemoryError,
    MemoryNetworkError,
    MemoryNotFoundError,
    MemoryProviderError,
    MemoryStorageError,
)
from mana_agent.memory.models import (
    MemoryContent,
    MemoryHealth,
    MemoryHealthStatus,
    MemoryRecord,
    MemoryScope,
    MemorySearchRequest,
    MemoryUpdateRequest,
    MemoryWriteRequest,
)
from mana_agent.memory.service import (
    CodingMemoryService,
    EvidenceMemory,
    MemoryService,
    MultiAgentMemoryService,
)
# Legacy data shapes remain public through this package while storage classes
# themselves stay isolated behind MemoryService.
from mana_agent.services.coding_memory_service import FlowSummary
from mana_agent.services.memory_service import (
    AgentDecisionMemoryRecord,
    FileReadMemoryRecord,
    ReadMode,
    ScopedMemoryBundle,
    TaskMemoryRecord,
    ToolExecutionMemoryRecord,
    VerificationMemoryRecord,
    normalize_file_path,
    normalize_text,
    normalize_tool_name,
    stable_hash,
    task_fingerprint,
    utc_iso,
)

__all__ = [
    "AgentDecisionMemoryRecord",
    "CodingMemoryService",
    "CapsuleAuthorizationError",
    "CapsuleBackend",
    "CapsuleConfig",
    "CapsuleLineage",
    "CapsuleMergeConflict",
    "CapsuleMergeRecord",
    "CapsuleProjection",
    "CapsuleReadRequest",
    "CapsuleRetentionConfig",
    "CapsuleScope",
    "CapsuleService",
    "CapsuleTaskContext",
    "DeleteMode",
    "EvidenceMemory",
    "FileReadMemoryRecord",
    "FlowSummary",
    "MemoryAuthenticationError",
    "MemoryBackend",
    "MemoryCapsule",
    "MemoryConfig",
    "MemoryConfigurationError",
    "MemoryContent",
    "MemoryDependencyError",
    "MemoryError",
    "MemoryHealth",
    "MemoryHealthStatus",
    "MemoryNetworkError",
    "MemoryNotFoundError",
    "MemoryProviderError",
    "MemoryPrincipal",
    "MemoryRecord",
    "MemoryScope",
    "MemorySearchRequest",
    "MemorySecretStore",
    "MemoryService",
    "MemoryStorageError",
    "MemoryUpdateRequest",
    "MemoryWriteRequest",
    "MultiAgentMemoryService",
    "MergeState",
    "MergeStrategy",
    "ReadMode",
    "ReviewState",
    "ScopedMemoryBundle",
    "TaskMemoryRecord",
    "ToolExecutionMemoryRecord",
    "TrustState",
    "AuthorizationDecision",
    "VerificationMemoryRecord",
    "normalize_file_path",
    "normalize_text",
    "normalize_tool_name",
    "stable_hash",
    "task_fingerprint",
    "utc_iso",
]
