"""Backend contract implemented by every memory provider."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from mana_agent.memory.models import (
    MemoryHealth,
    MemoryRecord,
    MemoryScope,
    MemorySearchRequest,
    MemoryUpdateRequest,
    MemoryWriteRequest,
)


@runtime_checkable
class MemoryBackend(Protocol):
    async def add(self, request: MemoryWriteRequest) -> MemoryRecord: ...
    async def search(self, request: MemorySearchRequest) -> list[MemoryRecord]: ...
    async def get(self, memory_id: str, scope: MemoryScope) -> MemoryRecord | None: ...
    async def update(self, memory_id: str, request: MemoryUpdateRequest) -> MemoryRecord: ...
    async def delete(self, memory_id: str, scope: MemoryScope) -> None: ...
    async def clear(self, scope: MemoryScope) -> None: ...
    async def healthcheck(self) -> MemoryHealth: ...
    async def close(self) -> None: ...


@runtime_checkable
class CapsuleBackend(Protocol):
    """Storage contract selected only behind the authorization service."""

    def create_capsule(self, capsule: Any) -> None: ...
    def get_capsule(self, capsule_id: str) -> Any | None: ...
    def query_capsules(self) -> list[Any]: ...
    def update_capsule(self, capsule: Any, *, expected_revision: int) -> None: ...
    def stage_capsule(self, capsule: Any) -> None: ...
    def list_staged_capsules(self) -> list[Any]: ...
    def merge_capsule(self, record: Any) -> None: ...
    def delete_capsule(self, capsule_id: str) -> bool: ...
    def get_lineage(self, capsule_id: str) -> Any: ...
    def record_access(self, entry: dict[str, Any]) -> None: ...
