"""Formal provider boundary."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol, runtime_checkable

from mana_agent.execution.models import (
    ArtifactRequest, ArtifactResult, ExecutionRequest, ExecutionResult,
    ProviderHealth, SandboxCapabilities, SandboxHandle, SandboxSpec,
    SnapshotRef, SnapshotRequest,
)


@runtime_checkable
class SandboxProvider(Protocol):
    name: str

    async def capabilities(self) -> SandboxCapabilities: ...
    async def provision(self, spec: SandboxSpec) -> SandboxHandle: ...
    async def start(self, handle: SandboxHandle) -> SandboxHandle: ...
    async def execute(self, handle: SandboxHandle, request: ExecutionRequest) -> ExecutionResult: ...
    async def upload(self, handle: SandboxHandle, source: Path, destination: str) -> None: ...
    async def download_artifacts(self, handle: SandboxHandle, request: ArtifactRequest) -> list[ArtifactResult]: ...
    async def snapshot(self, handle: SandboxHandle, request: SnapshotRequest) -> SnapshotRef: ...
    async def restore(self, snapshot: SnapshotRef, spec: SandboxSpec) -> SandboxHandle: ...
    async def suspend(self, handle: SandboxHandle) -> SandboxHandle: ...
    async def resume(self, handle: SandboxHandle) -> SandboxHandle: ...
    async def terminate(self, handle: SandboxHandle) -> None: ...
    async def cleanup(self, handle: SandboxHandle) -> None: ...
    async def healthcheck(self) -> ProviderHealth: ...
