"""Extension protocols for Teach Mode."""

from __future__ import annotations

from collections.abc import Callable, Iterable
from typing import Any, Protocol

from .models import ManaFlow, RecordedEvent, ReplayResult, SelectorCandidate, TeachSession, VerificationRule


class EventRecorder(Protocol):
    recorder_id: str
    def capabilities(self) -> set[str]: ...
    def start(self, session: TeachSession, emit: Callable[[RecordedEvent], None]) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def stop(self) -> None: ...


class PlatformAccessibilityAdapter(Protocol):
    platform: str
    def doctor(self) -> dict[str, Any]: ...
    def start(self, session: TeachSession, emit: Callable[[RecordedEvent], None]) -> None: ...
    def stop(self) -> None: ...


class BrowserEventSource(EventRecorder, Protocol):
    pass


class EventNormaliser(Protocol):
    def normalize(self, events: Iterable[RecordedEvent]) -> list[RecordedEvent]: ...


class WorkflowCompiler(Protocol):
    def compile(self, session: TeachSession, events: list[RecordedEvent]) -> ManaFlow: ...


class ReplayExecutor(Protocol):
    def replay(self, flow: ManaFlow, *, mode: str, inputs: dict[str, Any]) -> ReplayResult: ...


class VerificationProvider(Protocol):
    rule_type: str
    def verify(self, rule: VerificationRule, context: dict[str, Any]) -> tuple[bool, dict[str, Any]]: ...


class SelectorRepair(Protocol):
    def repair(self, flow: ManaFlow, step_id: str, candidate: SelectorCandidate) -> ManaFlow: ...


class SensitiveDataDetector(Protocol):
    def scan(self, value: Any) -> list[str]: ...
    def redact(self, value: Any) -> tuple[Any, list[str]]: ...


class FlowStorage(Protocol):
    def save_session(self, session: TeachSession) -> None: ...
    def load_session(self, session_id: str) -> TeachSession: ...
    def save_flow(self, flow: ManaFlow) -> None: ...
    def load_flow(self, flow_id: str, version: int | None = None) -> ManaFlow: ...


class FlowPackager(Protocol):
    def export(self, flow: ManaFlow, destination: str) -> str: ...
    def import_package(self, package: str) -> ManaFlow: ...
